[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # Difference is unmaintained, but we only use it for testing and it works fine
    "RUSTSEC-2020-0095",
]

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
exceptions = [
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
