[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0139", # ansi-term is Unmaintained - it is only a dev dependency
]

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
exceptions = [{ name = "instant", allow = ["BSD-3-Clause"] }]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
