all-features = true
# This is CI use only and doesn't affect the crates or downstream users
exclude = ["package"]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    # Use via redox_syscall which is removed from tempfile but not yet released
    # https://github.com/Stebalien/tempfile/pull/272
    { name = "bitflags", version = "=1.3.2" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
