on:
  push:
    branches:
      - main
  pull_request:

# Cancel PR actions on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # make sure all code has been formatted with rustfmt
      - name: check rustfmt
        run: cargo fmt -- --check --color always

      # run clippy to verify we have no warnings
      - run: cargo fetch
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --  -D warnings

  test:
    name: Test
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: macOS-14
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo run -p install -- ${{matrix.target}} __internal__binaries__ "${{github.workspace}}/bin"
      - run: cargo fetch
      - name: cargo test build
        run: cargo build --tests --release --all-features
      - name: cargo test
        run: cargo test --release --all-features

  # Remove this check if you don't use cargo-deny in the repo
  deny-check:
    name: cargo-deny
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: EmbarkStudios/cargo-deny-action@v1

  # Remove this check if you don't publish the crate(s) from this repo
  publish-check:
    name: Publish Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fetch
      - name: cargo publish check
        run: cargo publish --dry-run --manifest-path spirv-tools-sys/Cargo.toml
      - name: cargo publish check
        run: cargo publish --dry-run --manifest-path Cargo.toml
